spring.application.name=presence-server

spring.datasource.url=jdbc:postgresql://ep-raspy-cake-al3ljgcx-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require

# Utilisation de variables pour la s\u00e9curit\u00e9 (\u00e0 configurer dans ton IDE ou Render)
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate : Cr\u00e9e les tables automatiquement \u00e0 partir du code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port du serveur (par d\u00e9faut 8080)
server.address=0.0.0.0
server.port=${PORT:8080}
# La cl\u00e9 doit \u00eatre longue pour l'algorithme HS256
jwt.secret=${JWT_SECRET:MaCleSecreteParDefautTresLongueDePlusDe32Caracteres}
# Taille max fichier upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Ressources statiques (pour que Spring serve le dossier uploads)
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
# Configuration Email UniCheck
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unickeckalerte@gmail.com
spring.mail.password=ieps dwiw eked kzbg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true