spring.application.name=presence-server

spring.datasource.url=jdbc:postgresql://ep-raspy-cake-al3ljgcx-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:MaCleSecreteParDefautTresLongueDePlusDe32Caracteres}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# ── Email ────────────────────────────────────────────────────────────────────
# Configuration SMTP Brevo (Remplaçant de Gmail)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=ac7331001@smtp-brevo.com
spring.mail.password=${PASSWORD}

# Propriétés de sécurité
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
